# Project level information
project:
  name: "evs"
  displayName: "EVS application for device observation data."
  description: |
    This application will upload video and events data from handheld devices
    to Hanshow servers for processing. Event data is also uploaded for analysis.
  environment: dev
  labels:
    environment: "development"
    team: "Edge"
  quota:
    enabled: true
    hard:
      requests.cpu: "2"
      requests.memory: "4Gi"
      limits.cpu: "4"
      limits.memory: "8Gi"
      pods: "10"
      persistentvolumeclaims: "5"
# Application Global Configuration Items.
app:
  configData:
    serverPort:
      description: "The port the server will listen on for HTTP/S requests"
      value: 8080
      envVar: "SERVER_PORT"


  image:
    repository: xxx
    tag: 1.0.0
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: xxx
  # Number of instances to spin up.
  replicaCount: 1
  # Use the following to create annotations that can be applied to objects such as services,deployments etc.
  annotationSets:
    prometheus:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
    awsInternal:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    # These are istio annotations.
    istio:
      traffic.sidecar.istio.io/includeInboundPorts: "8080"
  # This is a Java 17 application we can drive the memory settings from this value alone.
  # If this does not work we can revert to the java_opts
  # We run QOS guaranteed so the limits and requests are the same.
  memory: 8Gi
  # See memory notes
  cpu: 1000

  persistence:
    dataVolume:
      enableKastenBackup: true
      storageClass: "local-storage"
      accessMode: ReadWriteOnce
      size: 20Gi
      name: evs-storage
      mountPath: /app/storage
  # This property repeatedly used in the following places:
  # server.port for springboot
  # services port
  # route port
  # readiness and other checks.
  apiPortKey: serverPort
  ports:
    serverPort:
      port:
        configDataKey: serverPort
      name: http_tomcat
      protocol: TCP
      description: "Port used by the application to run the server aka listening port."
    prometheusPort:
      port: 9090
      name: tcp_prom
      protocol: TCP
      description: "Used to configure the prometheus port for scraping"
    toms_port:
      port: 1443
      name: hacky_port
      description: "I own your data"

  services:
    - name: api
      type: ClusterIP
      description: " This service hosts the API ports so that we can expose it to the world"
      annotations:
        - prometheus
        - istio
      ports:
        - sourcePort: serverPort
          targetPort: serverPort
        - sourcePort: prometheusPort
          targetPort: prometheusPort
        - sourcePort: toms_port
          targetPort:  prometheusPort

  probes:
    # Probes mandatory
    liveness:
      tcpSocket:
        # reference the serverPort above.
        port: serverPort
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      tcpSocket:
        # reference the serverPort above.
        port: serverPort
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  env:
    SERVER_PORT: ""   # This will be filled by the Port using the key defined in the apiPortKey
    SERVER_SERVLET_CONTEXT_PATH: "/evs"
    SERVER_VERSION: "1.0.1"
    # Tomcat
    SERVER_TOMCAT_MAX_THREADS: "500"
    SERVER_TOMCAT_MIN_SPARE_THREADS: "200"
    SERVER_TOMCAT_MAX_CONNECTIONS: "20000"
    SERVER_TOMCAT_ACCEPT_COUNT: "1000"
    SERVER_TOMCAT_CONNECTION_TIMEOUT: "600000"
    SERVER_TOMCAT_KEEP_ALIVE_TIMEOUT: "600000"
    SERVER_TOMCAT_MAX_HTTP_FORM_POST_SIZE: "104857600"
    # openapi
    OPENAPI_USERS:
      - ak: "test1"
        sk: "000000"
        orgs:
          - "**"

    # Storage settings
    STORAGE_UPLOAD_MAX_CONCURRENCY: "5"
    STORAGE_FORBIDDEN_FILE_TYPES:
      - ".exe"
      - ".com"
      - ".dll"
      - ".sys"
      - ".scr"
      - ".bat"
      - ".cmd"
      - ".ps1"
      - ".psm1"
      - ".vbs"
      - ".vbe"
      - ".js"
      - ".jse"
      - ".wsf"
      - ".msc"
      - ".hta"
      - ".ear"
      - ".ipa"
      - ".docm"
      - ".xlsm"
      - ".pptm"
      - ".dotm"
      - ".xltm"
      - ".potm"
      - ".docx"
      - ".xlsx"
      - ".pptx"
      - ".rtf"
      - ".sql"
      - ".db"
      - ".sqlite"
      - ".mdb"
      - ".accdb"
      - ".ini"
      - ".key"
      - ".cert"
      - ".pfx"
      - ".php"
      - ".php3"
      - ".php4"
      - ".php5"
      - ".phtml"
      - ".asp"
      - ".aspx"
      - ".ascx"
      - ".jsp"
      - ".jspx"
      - ".java"
      - ".cgi"
      - ".pl"
      - ".lnk"
      - ".url"
      - ".desktop"
      - ".bin"
      - ".dat"
      - ".iso"
      - ".img"
      - ".vhd"
      - ".vmdk"
      - ".cab"
      - ".cmdlet"
    SCHEDULER_UPLOAD_START_TIME: "09:00"
    SCHEDULER_UPLOAD_END_TIME: "18:30"



#appConfig:
#  enabled: true
#  properties:
#    # server
#    #server.port: "8080"
#    #server.servlet.context-path: "/evs"
#    #server.version: "1.0.1"
#    # openapi
#    #    openapi.users: '[{"ak":"test1","sk":"000000","orgs":["**"]}]'
#    # buyboost  cloud service that we need to allow egress traffic to
#    buyboost.openapi.host: "http://172.16.125.46:8185/buyboost"
#    buyboost.openapi.ak: "test"
#    buyboost.openapi.sk: "000000"
#    # haidp cloud service that we need to allow egress traffic to
#    haidp.openapi.host: "http://10.13.108.6:9192/api1"
#    haidp.openapi.code: "edge"
#    haidp.openapi.desc: "EVS"
#    haidp.openapi.ak: "IJpBSwnImQArnXRarbod"
#    haidp.openapi.sk: "vr1C8tELhFoqK3SccL3vRcdZDKWsudJSSu9vkob8"
#    # scheduler (Local time, HH:mm)
#    #    scheduler.upload.start_time: "09:00"
#    #    scheduler.upload.end_time: "18:30"
#    # Tomcat
#    #    server.tomcat.max-threads: "500"
#    #    server.tomcat.min-spare-threads: "200"
#    #    server.tomcat.max-connections: "20000"
#    #    server.tomcat.accept-count: "1000"
#    #    server.tomcat.connection-timeout: "600000"
#    #    server.tomcat.keep-alive-timeout: "600000"
#    #    server.tomcat.max-http-form-post-size: "104857600"
#    # Storage
##    storage.upload.max_concurrency: "5"
##    storage.forbidden_file_types: ".exe,.com,.dll,.sys,.scr,.bat,.cmd,.ps1,.psm1,.vbs,.vbe,.js,.jse,.wsf,.msc,.hta,.ear,.ipa,.docm,.xlsm,.pptm,.dotm,.xltm,.potm,.docx,.xlsx,.pptx,.rtf,.sql,.db,.sqlite,.mdb,.accdb,.ini,.key,.cert,.pfx,.php,.php3,.php4,.php5,.phtml,.asp,.aspx,.ascx,.jsp,.jspx,.java,.cgi,.pl,.lnk,.url,.desktop,.bin,.dat,.iso,.img,.vhd,.vmdk,.cab,.cmdlet"
## 持久化存储
#
#
## 节点调度 Not needed we run a single node cluster.
##nodeSelector: {}
##tolerations: []
##affinity: {}
#
#
